[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
runner = """
ssh root@192.168.1.86 /root/rust-embedded
"""
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-L", "/usr/lib/gcc-cross/aarch64-linux-gnu/14/", 
]
